### ISSUE TITLE
`AbstractPlotting.vbox` alternatives

### ISSUE THREAD

**Issue by terasakisatoshi** [FluxML/Flux3D.jl#58]
It seems `AbstractPlotting.vbox` (which is used in this [docs](https://fluxml.ai/Flux3D.jl/dev/tutorials/fit_mesh/#Visualizing-TriMesh) ) is removed due to this commit https://github.com/JuliaPlots/Makie.jl/commit/fac052d9c39bc1b004676d0e9ad855cc61e84c4a we need to find alternatives that achieve this functionality.

I've implemented `visualize!` function that is similar to `Flux3D.visualize` except it accepts `axis3::Axis3`.

![image](https://user-images.githubusercontent.com/16760547/148958020-f19433b4-4477-425a-9681-0a020e709e20.png)

See gist https://gist.github.com/terasakisatoshi/00225d1dd053e1516e36ef97a9115ef5 to see the complete code.

If you like it, I will send a PR.

**Comment by nirmal-suthar** [comment]
Hi @terasakisatoshi, I didn't realise that `vbox` is removed.  Please go ahead with the PR, `visualize!` is a good alternative for providing flexibility while plotting.

**Comment by terasakisatoshi** [comment]
Good to know I will prepare a PR for this repo!

**Comment by terasakisatoshi** [comment]
We also need to update a sample code e.g. [here](https://github.com/FluxML/Flux3D.jl/blob/fb78320aeb7c56d4a27532f1dd468bdf26fda1dc/docs/src/api/visualize.md?plain=1#L12-L39). I would like to fix it after this pr #59 is merged.

**Comment by terasakisatoshi** [comment]
> We also need to update a sample code e.g. [here](https://github.com/FluxML/Flux3D.jl/blob/fb78320aeb7c56d4a27532f1dd468bdf26fda1dc/docs/src/api/visualize.md?plain=1#L12-L39). I would like to fix it after this pr #59 is merged.

https://github.com/FluxML/Flux3D.jl/pull/61 will resolve
